// <auto-generated />
namespace Recrutement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class erreurmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(erreurmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202006130253012_erreur-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
